//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Edziennik
{
    using System;
    using System.Collections.Generic;
    
    public partial class Grade
    {
        public int ID_Grade { get; set; }
        public int ID_Subject { get; set; }
        public int ID_Student { get; set; }
        public string Grade1 { get; set; }
        public System.DateTime Date { get; set; }
        public string Status { get; set; }
    
        public virtual Person Person { get; set; }
        public virtual Subject Subject { get; set; }
    }
}
