//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Edziennik
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubjectInPlan
    {
        public int ID_SubjectInPlan { get; set; }
        public int ID_Subject { get; set; }
        public string WeekDay { get; set; }
        public System.TimeSpan Hour { get; set; }
    
        public virtual Subject Subject { get; set; }
    }
}
